import type { KingdomKey } from '@/design/atoms/KingdomBadge'
import { resolveGlobalDexNumber } from '@/features/species/dex-number-registry'

export interface CreatureRosterItem {
  id: string
  commonName: string
  scientificName: string
  kingdom: string
  dexNumber: string
  description: string
  bonusXp: number
}

const CREATURE_BONUS_XP = 100

function slug(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

// [commonName, scientificName, kingdom, description]
// ~265 well-known species so Creature of the Week can run ~5 years (52×5) without
// repeating. Photos resolve automatically by name via useReferenceImage, so no bundled
// art is needed. Edit/extend freely — order doesn't matter (selection is week-hashed).
type Spec = [string, string, string, string]

const SPECS: Spec[] = [
  // ── Mammals ───────────────────────────────────────────────────────────────
  ['Red Fox', 'Vulpes vulpes', 'mammal', 'Adaptable and cunning — thrives from forests to city parks, most active at dawn and dusk.'],
  ['Arctic Fox', 'Vulpes lagopus', 'mammal', 'Wears a thick white coat in winter and turns brown for the tundra summer.'],
  ['Fennec Fox', 'Vulpes zerda', 'mammal', 'Those giant ears dump heat and catch the faintest desert rustle.'],
  ['Gray Wolf', 'Canis lupus', 'mammal', 'Highly social pack hunters whose howls carry for miles across the wild.'],
  ['Coyote', 'Canis latrans', 'mammal', 'Clever survivors found from deserts to suburbs, often heard yipping at dusk.'],
  ['Red Panda', 'Ailurus fulgens', 'mammal', 'A bamboo-loving forest dweller with a ringed tail it wraps up for warmth.'],
  ['Giant Panda', 'Ailuropoda melanoleuca', 'mammal', 'Spends most of the day munching bamboo in misty mountain forests.'],
  ['Snow Leopard', 'Panthera uncia', 'mammal', 'A ghost of the high Himalayas, padding silently across snowy ridgelines.'],
  ['African Lion', 'Panthera leo', 'mammal', 'The only truly social cat — prides rule the savanna together.'],
  ['Tiger', 'Panthera tigris', 'mammal', 'The largest cat on Earth, striped for the shadows of dense jungle.'],
  ['Cheetah', 'Acinonyx jubatus', 'mammal', 'Built for the sprint — the fastest land animal hits 70 mph in seconds.'],
  ['Leopard', 'Panthera pardus', 'mammal', 'Hauls prey into trees and hunts by stealth across half the world.'],
  ['Jaguar', 'Panthera onca', 'mammal', 'The Americas’ powerhouse cat, equally at home swimming or stalking.'],
  ['Cougar', 'Puma concolor', 'mammal', 'Also called puma or mountain lion — a wide-ranging ambush hunter.'],
  ['Eurasian Lynx', 'Lynx lynx', 'mammal', 'Tufted ears and huge paws help it hunt across snowy northern forests.'],
  ['Bobcat', 'Lynx rufus', 'mammal', 'A short-tailed wildcat that quietly patrols woodland edges at twilight.'],
  ['African Elephant', 'Loxodonta africana', 'mammal', 'The largest land animal, with a trunk dexterous enough to pick a single leaf.'],
  ['Asian Elephant', 'Elephas maximus', 'mammal', 'Smaller-eared cousin of the African elephant, revered across Asia.'],
  ['Giraffe', 'Giraffa camelopardalis', 'mammal', 'The tallest animal alive, browsing treetops with a long prehensile tongue.'],
  ['Plains Zebra', 'Equus quagga', 'mammal', 'No two stripe patterns are alike — a moving optical illusion to predators.'],
  ['Hippopotamus', 'Hippopotamus amphibius', 'mammal', 'Spends its days in rivers and grazes the banks by night.'],
  ['White Rhinoceros', 'Ceratotherium simum', 'mammal', 'A grazing tank with a wide square lip for cropping grass.'],
  ['Black Rhinoceros', 'Diceros bicornis', 'mammal', 'A browser with a hooked lip, more solitary and quick-tempered than its cousin.'],
  ['Common Warthog', 'Phacochoerus africanus', 'mammal', 'Kneels to root for food and sprints tail-up when startled.'],
  ['Meerkat', 'Suricata suricatta', 'mammal', 'Lives in tight desert gangs, always with one sentry standing guard.'],
  ['Spotted Hyena', 'Crocuta crocuta', 'mammal', 'A clever, vocal hunter whose laughing calls echo across the night savanna.'],
  ['Eastern Gray Kangaroo', 'Macropus giganteus', 'mammal', 'Bounds across Australian grasslands, carrying joeys in a cozy pouch.'],
  ['Koala', 'Phascolarctos cinereus', 'mammal', 'Sleeps up to 20 hours a day, fueled entirely by eucalyptus leaves.'],
  ['Common Wombat', 'Vombatus ursinus', 'mammal', 'A sturdy burrower that leaves famously cube-shaped droppings.'],
  ['Platypus', 'Ornithorhynchus anatinus', 'mammal', 'Lays eggs, senses prey electrically, and the male has venomous spurs.'],
  ['Tasmanian Devil', 'Sarcophilus harrisii', 'mammal', 'A feisty marsupial scavenger with one of the strongest bites for its size.'],
  ['Sugar Glider', 'Petaurus breviceps', 'mammal', 'Glides between trees on skin flaps, foraging for sap and insects at night.'],
  ['Brown Bear', 'Ursus arctos', 'mammal', 'A powerful omnivore that feasts on salmon runs and berries before winter.'],
  ['Polar Bear', 'Ursus maritimus', 'mammal', 'The Arctic’s apex hunter, roaming sea ice in search of seals.'],
  ['American Black Bear', 'Ursus americanus', 'mammal', 'A shy forest omnivore and surprisingly nimble tree climber.'],
  ['Sea Otter', 'Enhydra lutris', 'mammal', 'Floats on its back, cracks shells with rocks, and holds paws while sleeping.'],
  ['Eurasian Otter', 'Lutra lutra', 'mammal', 'A playful riverbank hunter, sleek and at home in the water.'],
  ['Raccoon', 'Procyon lotor', 'mammal', 'A masked, dexterous night forager that seems to wash its food.'],
  ['Red Squirrel', 'Sciurus vulgaris', 'mammal', 'A tufted-eared acrobat that stashes nuts across the forest for winter.'],
  ['Eastern Gray Squirrel', 'Sciurus carolinensis', 'mammal', 'A bold park resident, forever burying and rediscovering acorns.'],
  ['Eurasian Beaver', 'Castor fiber', 'mammal', 'Nature’s engineer — fells trees and builds dams that reshape whole streams.'],
  ['North American Porcupine', 'Erethizon dorsatum', 'mammal', 'Bristling with thousands of barbed quills it raises when threatened.'],
  ['European Hedgehog', 'Erinaceus europaeus', 'mammal', 'Rolls into a spiny ball and snuffles through hedgerows after dark.'],
  ['European Rabbit', 'Oryctolagus cuniculus', 'mammal', 'Lives in sprawling underground warrens and freezes at the first alarm.'],
  ['Mountain Hare', 'Lepus timidus', 'mammal', 'Swaps a brown summer coat for snowy white to vanish in winter.'],
  ['Capybara', 'Hydrochoerus hydrochaeris', 'mammal', 'The world’s largest rodent, an unflappable semi-aquatic grazer.'],
  ['Chimpanzee', 'Pan troglodytes', 'mammal', 'One of our closest relatives — uses tools and forms complex social bonds.'],
  ['Western Gorilla', 'Gorilla gorilla', 'mammal', 'Gentle forest giants led by a commanding silverback.'],
  ['Bornean Orangutan', 'Pongo pygmaeus', 'mammal', 'A thoughtful, red-haired ape that builds a fresh treetop nest each night.'],
  ['Ring-tailed Lemur', 'Lemur catta', 'mammal', 'Sunbathes in troops and signals with that unmistakable striped tail.'],
  ['Mandrill', 'Mandrillus sphinx', 'mammal', 'The most colorful mammal — vivid face and rump light up the rainforest floor.'],
  ['Japanese Macaque', 'Macaca fuscata', 'mammal', 'Famous for soaking in steaming hot springs through the snowy winter.'],
  ['Brown-throated Sloth', 'Bradypus variegatus', 'mammal', 'Moves so slowly that algae grows in its fur, the perfect camouflage.'],
  ['Giant Anteater', 'Myrmecophaga tridactyla', 'mammal', 'Sweeps up thousands of ants a day with a two-foot sticky tongue.'],
  ['Nine-banded Armadillo', 'Dasypus novemcinctus', 'mammal', 'Armored forager that can hold its breath to cross the bottom of a stream.'],
  ['Sunda Pangolin', 'Manis javanica', 'mammal', 'The only scaly mammal, rolling into an armored ball when threatened.'],
  ['Aardvark', 'Orycteropus afer', 'mammal', 'A nocturnal digger that tears open termite mounds with powerful claws.'],
  ['Moose', 'Alces alces', 'mammal', 'The towering giant of northern forests, wading into lakes to feed.'],
  ['Red Deer', 'Cervus elaphus', 'mammal', 'Stags clash antlers and bellow across the hills each autumn rut.'],
  ['White-tailed Deer', 'Odocoileus virginianus', 'mammal', 'Flashes a white tail like a flag when it bounds away through the trees.'],
  ['Reindeer', 'Rangifer tarandus', 'mammal', 'The only deer where both sexes grow antlers, built for Arctic migrations.'],
  ['American Bison', 'Bison bison', 'mammal', 'North America’s largest land animal, thundering across the prairie.'],
  ['Blue Wildebeest', 'Connochaetes taurinus', 'mammal', 'Gathers by the million for one of Earth’s greatest migrations.'],
  ['Impala', 'Aepyceros melampus', 'mammal', 'An elegant antelope that leaps ten feet high to escape predators.'],
  ['Alpine Ibex', 'Capra ibex', 'mammal', 'Scales near-vertical cliffs on hooves built for impossible footing.'],
  ['Bactrian Camel', 'Camelus bactrianus', 'mammal', 'Two humps of fat fuel long treks across freezing Central Asian deserts.'],
  ['Llama', 'Lama glama', 'mammal', 'A sure-footed Andean pack animal known for its expressive face.'],
  ['Common Bottlenose Dolphin', 'Tursiops truncatus', 'mammal', 'Playful and brilliant, hunting in coordinated pods with clicks and whistles.'],
  ['Orca', 'Orcinus orca', 'mammal', 'The ocean’s top predator, hunting in tight family pods with unique dialects.'],
  ['Humpback Whale', 'Megaptera novaeangliae', 'mammal', 'Breaches the surface and sings haunting songs that travel for miles.'],
  ['Blue Whale', 'Balaenoptera musculus', 'mammal', 'The largest animal to ever live — its heart is the size of a small car.'],
  ['Narwhal', 'Monodon monoceros', 'mammal', 'The unicorn of the sea, its tusk a spiral tooth full of nerves.'],
  ['West Indian Manatee', 'Trichechus manatus', 'mammal', 'A gentle, slow-moving grazer drifting through warm coastal shallows.'],
  ['Walrus', 'Odobenus rosmarus', 'mammal', 'Hauls out on the ice in great herds, using tusks to climb and dig clams.'],
  ['California Sea Lion', 'Zalophus californianus', 'mammal', 'A noisy, acrobatic swimmer that barks from sun-warmed rocks.'],

  // ── Birds ─────────────────────────────────────────────────────────────────
  ['Northern Cardinal', 'Cardinalis cardinalis', 'bird', 'The male’s vivid red is unmistakable; listen for its clear dawn whistle.'],
  ['Barn Owl', 'Tyto alba', 'bird', 'A silent flier with a heart-shaped face that hunts by sound alone.'],
  ['Great Horned Owl', 'Bubo virginianus', 'bird', 'A powerful nocturnal hunter known for its deep, resonant hoots.'],
  ['Snowy Owl', 'Bubo scandiacus', 'bird', 'A ghostly white owl of the Arctic that hunts even in daylight.'],
  ['Bald Eagle', 'Haliaeetus leucocephalus', 'bird', 'A fish-snatching raptor and the soaring emblem of North America.'],
  ['Golden Eagle', 'Aquila chrysaetos', 'bird', 'A mountain hunter with a seven-foot wingspan and breathtaking dives.'],
  ['Peregrine Falcon', 'Falco peregrinus', 'bird', 'The fastest animal alive, stooping on prey at over 200 mph.'],
  ['Osprey', 'Pandion haliaetus', 'bird', 'A fish hawk that plunges talons-first to pluck prey from the water.'],
  ['Red-tailed Hawk', 'Buteo jamaicensis', 'bird', 'A roadside soarer whose piercing scream is heard in countless films.'],
  ['American Robin', 'Turdus migratorius', 'bird', 'A cheerful lawn forager whose song heralds the arrival of spring.'],
  ['Blue Jay', 'Cyanocitta cristata', 'bird', 'A bold, brainy corvid that caches acorns and mimics hawk calls.'],
  ['American Goldfinch', 'Spinus tristis', 'bird', 'Turns brilliant lemon-yellow in summer and flies in bouncing arcs.'],
  ['Ruby-throated Hummingbird', 'Archilochus colubris', 'bird', 'Hovers on a blur of wings, its throat flashing like a ruby.'],
  ['Mute Swan', 'Cygnus olor', 'bird', 'Glides serenely on still water, wings arched in an elegant curve.'],
  ['Mallard', 'Anas platyrhynchos', 'bird', 'The familiar pond duck — the glossy-green-headed ancestor of farm ducks.'],
  ['Canada Goose', 'Branta canadensis', 'bird', 'Honks overhead in long V-formations on its seasonal migrations.'],
  ['Great Blue Heron', 'Ardea herodias', 'bird', 'Stands statue-still in the shallows before spearing fish with a stab.'],
  ['American Flamingo', 'Phoenicopterus ruber', 'bird', 'Wades on stilt legs, its pink hue borrowed from the shrimp it eats.'],
  ['Atlantic Puffin', 'Fratercula arctica', 'bird', 'A clown-faced seabird that carries beakfuls of fish back to cliff burrows.'],
  ['King Penguin', 'Aptenodytes patagonicus', 'bird', 'A dapper diver that huddles in vast colonies on subantarctic shores.'],
  ['Emperor Penguin', 'Aptenodytes forsteri', 'bird', 'Endures the brutal Antarctic winter, balancing a single egg on its feet.'],
  ['Toco Toucan', 'Ramphastos toco', 'bird', 'That enormous colorful bill is surprisingly light and helps it stay cool.'],
  ['Scarlet Macaw', 'Ara macao', 'bird', 'A long-tailed rainbow of a parrot that mates for life and is wonderfully loud.'],
  ['Resplendent Quetzal', 'Pharomachrus mocinno', 'bird', 'A shimmering cloud-forest jewel with streaming emerald tail plumes.'],
  ['Common Kingfisher', 'Alcedo atthis', 'bird', 'An electric-blue flash that dives like a dart for tiny fish.'],
  ['Pileated Woodpecker', 'Dryocopus pileatus', 'bird', 'A crow-sized, red-crested driller that chisels rectangular holes in trees.'],
  ['European Robin', 'Erithacus rubecula', 'bird', 'A friendly red-breasted garden companion that sings even in winter.'],
  ['Barn Swallow', 'Hirundo rustica', 'bird', 'A graceful aerial acrobat that builds mud nests under eaves.'],
  ['Common Raven', 'Corvus corax', 'bird', 'A brilliant problem-solver that tumbles and rolls in the sky for fun.'],
  ['Indian Peafowl', 'Pavo cristatus', 'bird', 'The peacock fans a shimmering eyed train in one of nature’s great displays.'],
  ['Wild Turkey', 'Meleagris gallopavo', 'bird', 'A surprisingly fast, sharp-eyed forager that roosts high in the trees.'],
  ['Greater Roadrunner', 'Geococcyx californianus', 'bird', 'A desert sprinter that would rather run than fly, snatching lizards on the dash.'],
  ['American Kestrel', 'Falco sparverius', 'bird', 'A jewel-toned little falcon that hovers over fields hunting insects and mice.'],
  ['Northern Mockingbird', 'Mimus polyglottos', 'bird', 'A tireless mimic that strings together the songs of dozens of other birds.'],
  ['Black-capped Chickadee', 'Poecile atricapillus', 'bird', 'A tiny, fearless feeder visitor that names itself with its chick-a-dee call.'],
  ['Western Bluebird', 'Sialia mexicana', 'bird', 'A sky-blue orchard bird that nests happily in boxes and old woodpecker holes.'],
  ['Cedar Waxwing', 'Bombycilla cedrorum', 'bird', 'A sleek, masked berry-lover with waxy red wingtips, often in roving flocks.'],
  ['Snowy Egret', 'Egretta thula', 'bird', 'Shuffles golden feet to stir up prey in the shallows, all in elegant white.'],
  ['Wood Duck', 'Aix sponsa', 'bird', 'Arguably the most ornate duck, nesting in tree cavities above the water.'],
  ['Sandhill Crane', 'Antigone canadensis', 'bird', 'A tall, bugling crane that gathers by the thousands on its migrations.'],
  ['Anna’s Hummingbird', 'Calypte anna', 'bird', 'The male dive-bombs in courtship, its throat flashing hot pink.'],
  ['Rainbow Lorikeet', 'Trichoglossus moluccanus', 'bird', 'A riot of color that brush-tongues nectar from flowering trees.'],
  ['Laughing Kookaburra', 'Dacelo novaeguineae', 'bird', 'Its cackling chorus is the unmistakable sound of the Australian bush.'],
  ['Eurasian Blue Tit', 'Cyanistes caeruleus', 'bird', 'A tiny acrobatic garden bird in cheerful blue and yellow.'],
  ['Greater Flamingo', 'Phoenicopterus roseus', 'bird', 'Filters tiny food from saltpans, gathering in spectacular pink crowds.'],
  ['Secretarybird', 'Sagittarius serpentarius', 'bird', 'A long-legged raptor that strides the savanna stamping snakes.'],
  ['Hoopoe', 'Upupa epops', 'bird', 'Raises a fan-like crest and probes the soil with a long curved bill.'],
  ['Common Loon', 'Gavia immer', 'bird', 'Its haunting wail drifts across northern lakes on summer nights.'],
  ['Steller’s Jay', 'Cyanocitta stelleri', 'bird', 'A dark-crested mountain jay, bold around campsites and pine forests.'],
  ['Painted Bunting', 'Passerina ciris', 'bird', 'Looks dipped in paint — blue head, red body, and green back.'],
  ['Eurasian Magpie', 'Pica pica', 'bird', 'A glossy, clever corvid that recognizes itself in a mirror.'],
  ['Great Egret', 'Ardea alba', 'bird', 'Wades the wetlands in pure white, spearing fish with a lightning neck.'],
  ['Belted Kingfisher', 'Megaceryle alcyon', 'bird', 'Rattles along rivers before plunging headfirst after fish.'],
  ['Tundra Swan', 'Cygnus columbianus', 'bird', 'Crosses continents in great flocks between Arctic tundra and mild coasts.'],
  ['Eurasian Eagle-Owl', 'Bubo bubo', 'bird', 'One of the largest owls, with fiery orange eyes and a deep booming hoot.'],

  // ── Reptiles ──────────────────────────────────────────────────────────────
  ['Crested Gecko', 'Correlophus ciliatus', 'reptile', 'Clings to leaves with sticky toe pads and comes alive at dusk.'],
  ['Leopard Gecko', 'Eublepharis macularius', 'reptile', 'A gentle, spotted desert gecko that can drop and regrow its tail.'],
  ['Tokay Gecko', 'Gekko gecko', 'reptile', 'A big, bold gecko that barks its own name — “to-kay!” — after dark.'],
  ['Green Iguana', 'Iguana iguana', 'reptile', 'A tree-loving herbivore that basks high in the canopy and dives to escape.'],
  ['Komodo Dragon', 'Varanus komodoensis', 'reptile', 'The largest lizard on Earth, an ambush hunter with a venomous bite.'],
  ['Veiled Chameleon', 'Chamaeleo calyptratus', 'reptile', 'Swivels independent eyes and fires a tongue longer than its body.'],
  ['Panther Chameleon', 'Furcifer pardalis', 'reptile', 'A living kaleidoscope, shifting color with mood and temperature.'],
  ['Frilled Lizard', 'Chlamydosaurus kingii', 'reptile', 'Flares a startling neck frill and bolts upright on two legs.'],
  ['Bearded Dragon', 'Pogona vitticeps', 'reptile', 'Puffs a spiny “beard” and waves an arm to greet other dragons.'],
  ['Green Sea Turtle', 'Chelonia mydas', 'reptile', 'Glides across oceans and returns to the very beach where it hatched.'],
  ['Leatherback Sea Turtle', 'Dermochelys coriacea', 'reptile', 'The largest turtle, diving deep for jellyfish in cold open seas.'],
  ['Eastern Box Turtle', 'Terrapene carolina', 'reptile', 'Closes its domed shell completely, roaming damp woodlands for decades.'],
  ['Galápagos Tortoise', 'Chelonoidis niger', 'reptile', 'A gentle giant that can live well past a hundred years.'],
  ['Red-eared Slider', 'Trachemys scripta elegans', 'reptile', 'A pond basker that stacks on logs and slides off at the slightest noise.'],
  ['American Alligator', 'Alligator mississippiensis', 'reptile', 'A swamp survivor from the age of dinosaurs, bellowing in spring.'],
  ['Saltwater Crocodile', 'Crocodylus porosus', 'reptile', 'The largest living reptile, ruling rivers and coastlines as a stealthy ambusher.'],
  ['Gharial', 'Gavialis gangeticus', 'reptile', 'A river crocodilian with a slender snout perfectly shaped for catching fish.'],
  ['Ball Python', 'Python regius', 'reptile', 'A mild-mannered constrictor that curls into a tight ball when nervous.'],
  ['Green Anaconda', 'Eunectes murinus', 'reptile', 'The heaviest snake alive, lurking in slow Amazon waters.'],
  ['Reticulated Python', 'Malayopython reticulatus', 'reptile', 'The longest snake on Earth, patterned in an intricate net of diamonds.'],
  ['King Cobra', 'Ophiophagus hannah', 'reptile', 'The longest venomous snake — it rears tall and even eats other snakes.'],
  ['Eastern Diamondback Rattlesnake', 'Crotalus adamanteus', 'reptile', 'Warns with a buzzing tail before it ever considers striking.'],
  ['Corn Snake', 'Pantherophis guttatus', 'reptile', 'A gentle, colorful rat-hunter and a favorite first pet snake.'],
  ['Boa Constrictor', 'Boa constrictor', 'reptile', 'A powerful ambush predator that squeezes rather than envenomates.'],
  ['Gila Monster', 'Heloderma suspectum', 'reptile', 'A slow, beaded desert lizard and one of the few venomous ones.'],
  ['Marine Iguana', 'Amblyrhynchus cristatus', 'reptile', 'The only sea-going lizard, grazing algae on Galápagos reefs.'],
  ['Tuatara', 'Sphenodon punctatus', 'reptile', 'A living fossil from New Zealand, the last of an ancient reptile order.'],
  ['Green Basilisk', 'Basiliscus plumifrons', 'reptile', 'The “Jesus Christ lizard” sprints across the surface of the water.'],
  ['Thorny Devil', 'Moloch horridus', 'reptile', 'A spiky desert lizard that channels dew along its skin straight to its mouth.'],
  ['Eastern Blue-tongued Skink', 'Tiliqua scincoides', 'reptile', 'Flashes a startling blue tongue to bluff its way out of trouble.'],

  // ── Amphibians ────────────────────────────────────────────────────────────
  ['Green Tree Frog', 'Hyla cinerea', 'amphibian', 'Clings to reeds near still water, its bright skin melting into the foliage.'],
  ['Red-eyed Tree Frog', 'Agalychnis callidryas', 'amphibian', 'Flashes ruby eyes and orange feet to startle predators in the rainforest.'],
  ['Poison Dart Frog', 'Dendrobates tinctorius', 'amphibian', 'Tiny and dazzling — its bold colors warn of powerful skin toxins.'],
  ['American Bullfrog', 'Lithobates catesbeianus', 'amphibian', 'A booming jug-o-rum call rolls across ponds on warm summer nights.'],
  ['Common Toad', 'Bufo bufo', 'amphibian', 'A warty garden wanderer that returns to the same pond to breed each spring.'],
  ['Axolotl', 'Ambystoma mexicanum', 'amphibian', 'A smiling salamander that never grows up — and can regrow whole limbs.'],
  ['Fire Salamander', 'Salamandra salamandra', 'amphibian', 'Bold black-and-yellow patterns warn that its skin is best left alone.'],
  ['Tiger Salamander', 'Ambystoma tigrinum', 'amphibian', 'A burly burrowing salamander that emerges on rainy nights to breed.'],
  ['Eastern Newt', 'Notophthalmus viridescens', 'amphibian', 'Spends a fiery-orange teenage “eft” stage wandering the forest floor.'],
  ['Wood Frog', 'Lithobates sylvaticus', 'amphibian', 'Freezes nearly solid through winter, then thaws back to life in spring.'],
  ['Goliath Frog', 'Conraua goliath', 'amphibian', 'The largest frog on Earth, big enough to fill both hands.'],
  ['Glass Frog', 'Hyalinobatrachium valerioi', 'amphibian', 'Its belly skin is so clear you can watch its heart beat.'],
  ['Spotted Salamander', 'Ambystoma maculatum', 'amphibian', 'A secretive forest dweller dotted with cheerful yellow spots.'],
  ['Cane Toad', 'Rhinella marina', 'amphibian', 'A huge, hardy toad — a voracious eater wherever it turns up.'],
  ['Surinam Toad', 'Pipa pipa', 'amphibian', 'A flat, leaf-like swimmer whose young erupt from pockets in its back.'],
  ['Pacman Frog', 'Ceratophrys ornata', 'amphibian', 'A round, big-mouthed ambusher that lies in wait to gulp passing prey.'],

  // ── Fish ──────────────────────────────────────────────────────────────────
  ['Clownfish', 'Amphiprion ocellaris', 'fish', 'Shelters unharmed among stinging anemone tentacles on the reef.'],
  ['Mandarinfish', 'Synchiropus splendidus', 'fish', 'A tiny reef fish painted in swirling electric blues and oranges.'],
  ['Koi', 'Cyprinus rubrofuscus', 'fish', 'Living jewels of garden ponds, some living over a century.'],
  ['Betta', 'Betta splendens', 'fish', 'The siamese fighting fish flares dramatic, flowing fins.'],
  ['Great White Shark', 'Carcharodon carcharias', 'fish', 'The ocean’s iconic apex predator, sensing a drop of blood from far off.'],
  ['Whale Shark', 'Rhincodon typus', 'fish', 'The largest fish alive, a gentle giant that filters tiny plankton.'],
  ['Hammerhead Shark', 'Sphyrna mokarran', 'fish', 'Its wide-set eyes on a flat head give it 360-degree vision.'],
  ['Manta Ray', 'Mobula birostris', 'fish', 'Soars through open water on wings spanning more than twenty feet.'],
  ['Seahorse', 'Hippocampus kuda', 'fish', 'Anchors with a curling tail, and it’s the male that carries the babies.'],
  ['Leafy Seadragon', 'Phycodurus eques', 'fish', 'Drifts disguised as floating seaweed off southern Australia.'],
  ['Lionfish', 'Pterois volitans', 'fish', 'Fans out venomous, feathery spines as a bold warning on the reef.'],
  ['Blue Tang', 'Paracanthurus hepatus', 'fish', 'A brilliant blue reef fish with a hidden, scalpel-sharp tail spine.'],
  ['Queen Angelfish', 'Holacanthus ciliaris', 'fish', 'A radiant reef beauty in electric blue and gold.'],
  ['Parrotfish', 'Scarus frenatus', 'fish', 'Crunches coral with a beak-like mouth and helps make white-sand beaches.'],
  ['Moorish Idol', 'Zanclus cornutus', 'fish', 'Sweeps a long trailing fin filament above striking black-and-yellow bands.'],
  ['Atlantic Bluefin Tuna', 'Thunnus thynnus', 'fish', 'A warm-blooded torpedo built for crossing entire oceans at speed.'],
  ['Atlantic Salmon', 'Salmo salar', 'fish', 'Leaps waterfalls on an epic journey back to the river of its birth.'],
  ['Rainbow Trout', 'Oncorhynchus mykiss', 'fish', 'A cold-stream favorite, flanks shining with a rosy stripe.'],
  ['Ocean Sunfish', 'Mola mola', 'fish', 'The heaviest bony fish, basking on its side at the surface.'],
  ['Electric Eel', 'Electrophorus electricus', 'fish', 'Generates jolts strong enough to stun prey in murky Amazon waters.'],
  ['Pufferfish', 'Arothron meleagris', 'fish', 'Gulps water to balloon into a spiny, hard-to-swallow ball.'],
  ['Archerfish', 'Toxotes jaculatrix', 'fish', 'Shoots a precise jet of water to knock insects off overhanging leaves.'],
  ['Garibaldi', 'Hypsypops rubicundus', 'fish', 'A brilliant orange damselfish that fiercely guards its patch of reef.'],
  ['Atlantic Cod', 'Gadus morhua', 'fish', 'A cold-water schooling fish that shaped the history of seafaring towns.'],
  ['Giant Oarfish', 'Regalecus glesne', 'fish', 'A ribbon-like deep-sea giant once mistaken for a sea serpent.'],
  ['Discus', 'Symphysodon aequifasciatus', 'fish', 'A disc-shaped Amazon cichlid prized for its painterly patterns.'],
  ['Yellow Tang', 'Zebrasoma flavescens', 'fish', 'A glowing lemon-yellow reef grazer that fades to grey at night.'],
  ['Common Carp', 'Cyprinus carpio', 'fish', 'A hardy, whiskered bottom-feeder found in waters around the world.'],

  // ── Insects ───────────────────────────────────────────────────────────────
  ['Monarch Butterfly', 'Danaus plexippus', 'insect', 'Migrates thousands of miles, drawn to milkweed every summer.'],
  ['Common Bumble Bee', 'Bombus terrestris', 'insect', 'A fuzzy, vital pollinator humming between garden flowers.'],
  ['Western Honey Bee', 'Apis mellifera', 'insect', 'Dances to share directions and turns nectar into golden honey.'],
  ['Seven-spot Ladybird', 'Coccinella septempunctata', 'insect', 'A gardener’s friend that devours aphids by the hundreds.'],
  ['Blue Morpho', 'Morpho menelaus', 'insect', 'Flashes shimmering iridescent blue wings through rainforest light.'],
  ['Atlas Moth', 'Attacus atlas', 'insect', 'One of the largest moths, its wingtips shaped like snake heads.'],
  ['Luna Moth', 'Actias luna', 'insect', 'A pale green giant with long tails that confuse hunting bats.'],
  ['Emperor Dragonfly', 'Anax imperator', 'insect', 'A fast aerial hunter that snatches insects on the wing over ponds.'],
  ['Praying Mantis', 'Mantis religiosa', 'insect', 'Waits motionless with folded forelegs, then strikes in a blink.'],
  ['Orchid Mantis', 'Hymenopus coronatus', 'insect', 'Disguised as a pink blossom to ambush the pollinators that visit.'],
  ['Firefly', 'Photinus pyralis', 'insect', 'Blinks a cold yellow light to signal across warm summer meadows.'],
  ['Hercules Beetle', 'Dynastes hercules', 'insect', 'A horned heavyweight that can lift many times its own weight.'],
  ['Stag Beetle', 'Lucanus cervus', 'insect', 'Males wrestle with antler-like jaws over the best perches.'],
  ['Jewel Beetle', 'Chrysochroa fulgidissima', 'insect', 'Armored in metallic rainbow color that never seems to fade.'],
  ['Leafcutter Ant', 'Atta cephalotes', 'insect', 'Marches with leaf scraps to farm a fungus garden underground.'],
  ['Carpenter Bee', 'Xylocopa virginica', 'insect', 'A big, shiny bee that drills tidy tunnels into wood to nest.'],
  ['Green Darner', 'Anax junius', 'insect', 'A migratory dragonfly that patrols wetlands on glassy wings.'],
  ['Cecropia Moth', 'Hyalophora cecropia', 'insect', 'North America’s largest native moth, with banded reddish wings.'],
  ['Painted Lady', 'Vanessa cardui', 'insect', 'A wanderer butterfly found on nearly every continent.'],
  ['Eastern Tiger Swallowtail', 'Papilio glaucus', 'insect', 'A big yellow-and-black flutterer of sunny woodland edges.'],
  ['Cicada', 'Magicicada septendecim', 'insect', 'Some broods wait seventeen years underground before a roaring summer chorus.'],
  ['Giant Walking Stick', 'Phasmatodea', 'insect', 'A master of disguise, frozen still as a twig among the leaves.'],
  ['Rhinoceros Beetle', 'Oryctes nasicornis', 'insect', 'Sports a curved horn and astonishing strength for its size.'],
  ['Velvet Ant', 'Dasymutilla occidentalis', 'insect', 'A fuzzy red wasp nicknamed “cow killer” for its memorable sting.'],
  ['Honey Pot Ant', 'Myrmecocystus mexicanus', 'insect', 'Living larders — some workers swell with nectar to feed the colony.'],
  ['Goliath Beetle', 'Goliathus goliatus', 'insect', 'Among the heaviest insects, a bulky giant of African forests.'],
  ['Common Green Lacewing', 'Chrysoperla carnea', 'insect', 'Delicate and golden-eyed, its larvae are voracious aphid hunters.'],
  ['Mantidfly', 'Climaciella brunnea', 'insect', 'Part lacewing, part mantis lookalike — a curious garden ambusher.'],

  // ── Arachnids ─────────────────────────────────────────────────────────────
  ['Mexican Redknee Tarantula', 'Brachypelma hamorii', 'arachnid', 'A docile, long-lived tarantula with striking orange-banded knees.'],
  ['Goliath Birdeater', 'Theraphosa blondi', 'arachnid', 'The world’s heaviest spider, big enough to span a dinner plate.'],
  ['Jumping Spider', 'Phidippus audax', 'arachnid', 'Big-eyed and curious, it pounces on prey with a silk safety line.'],
  ['Garden Orb-weaver', 'Araneus diadematus', 'arachnid', 'Spins a fresh dewy wheel of a web across the garden each morning.'],
  ['Black Widow', 'Latrodectus mactans', 'arachnid', 'Glossy black with a red hourglass, shy but famously venomous.'],
  ['Emperor Scorpion', 'Pandinus imperator', 'arachnid', 'A big, glossy scorpion that glows an eerie blue under UV light.'],
  ['Wolf Spider', 'Hogna carolinensis', 'arachnid', 'A ground hunter that chases prey down instead of building a web.'],
  ['Harvestman', 'Phalangium opilio', 'arachnid', 'The “daddy longlegs” — not a true spider and completely harmless.'],
  ['Peacock Spider', 'Maratus volans', 'arachnid', 'A tiny male raises a vivid fan and dances to win a mate.'],
  ['Bark Scorpion', 'Centruroides sculpturatus', 'arachnid', 'A slender desert climber that hides under bark and stones.'],
  ['Ladybird Spider', 'Eresus sandaliatus', 'arachnid', 'The male wears a striking red, spotted back like a tiny ladybird.'],
  ['Huntsman Spider', 'Heteropoda venatoria', 'arachnid', 'A long-legged, fast wall-walker that quietly keeps homes pest-free.'],

  // ── Molluscs ──────────────────────────────────────────────────────────────
  ['Common Octopus', 'Octopus vulgaris', 'mollusc', 'A shape-shifting genius that solves puzzles and vanishes into the reef.'],
  ['Giant Pacific Octopus', 'Enteroctopus dofleini', 'mollusc', 'The largest octopus, with an arm span wider than a car.'],
  ['Common Cuttlefish', 'Sepia officinalis', 'mollusc', 'Hypnotizes prey with rippling waves of color across its skin.'],
  ['Bigfin Reef Squid', 'Sepioteuthis lessoniana', 'mollusc', 'Hovers in the shallows, flashing patterns to talk to its school.'],
  ['Nautilus', 'Nautilus pompilius', 'mollusc', 'A living fossil that jets through the deep in a spiral pearly shell.'],
  ['Garden Snail', 'Cornu aspersum', 'mollusc', 'Carries its spiral home everywhere, gliding on a ribbon of slime.'],
  ['Banana Slug', 'Ariolimax columbianus', 'mollusc', 'A bright yellow forest recycler munching through fallen leaves.'],
  ['Spanish Dancer', 'Hexabranchus sanguineus', 'mollusc', 'A large sea slug that swims with flamenco-like ruffles of red.'],
  ['Blue Dragon', 'Glaucus atlanticus', 'mollusc', 'A tiny ocean-drifting sea slug shaped like a winged blue dragon.'],
  ['Giant Clam', 'Tridacna gigas', 'mollusc', 'The largest shellfish, its rippling mantle glowing with living color.'],
  ['Queen Conch', 'Aliger gigas', 'mollusc', 'A grazer of seagrass beds inside a famous pink-lipped spiral shell.'],
  ['Chambered Scallop', 'Pecten maximus', 'mollusc', 'Claps its fluted shell to swim in surprising little bursts.'],
  ['Blue-ringed Octopus', 'Hapalochlaena lunulata', 'mollusc', 'Tiny and beautiful, it pulses electric-blue rings as a serious warning.'],
  ['Flamboyant Cuttlefish', 'Metasepia pfefferi', 'mollusc', 'Walks the seafloor flashing bold pulses of color and pattern.'],

  // ── More favorites ────────────────────────────────────────────────────────
  ['South American Tapir', 'Tapirus terrestris', 'mammal', 'A shy, pig-like browser with a flexible little trunk for a nose.'],
  ['Okapi', 'Okapia johnstoni', 'mammal', 'A secretive forest cousin of the giraffe with zebra-striped legs.'],
  ['Serval', 'Leptailurus serval', 'mammal', 'Long-legged and big-eared, it pounces high to pin prey in tall grass.'],
  ['Wolverine', 'Gulo gulo', 'mammal', 'A muscular, fearless scavenger that ranges huge distances across the north.'],
  ['Honey Badger', 'Mellivora capensis', 'mammal', 'Famously tough and clever, it digs out almost any meal it wants.'],
  ['Shoebill', 'Balaeniceps rex', 'bird', 'Stands statue-still in the swamp behind a massive, shoe-shaped bill.'],
  ['Andean Condor', 'Vultur gryphus', 'bird', 'One of the largest flying birds, riding mountain thermals for hours.'],
  ['Kakapo', 'Strigops habroptilus', 'bird', 'A rare, flightless night parrot from New Zealand that booms to attract a mate.'],
  ['Green Tree Python', 'Morelia viridis', 'reptile', 'Drapes in tidy coils over a branch, vivid green by day in the canopy.'],
  ['Giant Moray', 'Gymnothorax javanicus', 'fish', 'Lurks in reef crevices, breathing through a constantly gaping jaw.'],
  ['Madagascan Sunset Moth', 'Chrysiridia rhipheus', 'insect', 'A day-flying moth shimmering in iridescent rainbow scales.'],
  ['Olm', 'Proteus anguinus', 'amphibian', 'A pale, blind cave salamander that can live for a century in the dark.'],
]

export const CREATURE_ROSTER: CreatureRosterItem[] = SPECS.map(([commonName, scientificName, kingdom, description]) => {
  const id = slug(commonName)
  return {
    id,
    commonName,
    scientificName,
    kingdom,
    dexNumber: resolveGlobalDexNumber({ commonName, latinName: scientificName, kingdom: kingdom as KingdomKey, lookupId: id }),
    description,
    bonusXp: CREATURE_BONUS_XP,
  }
})
